name: Deploy GKE
inputs:
  image:
    description: |-
      Image to be deployed
    required: true

  app_name:
    description: |-
      Application name of the Kubernetes deployment
    required: true

  region:
    description: |-
      Region/zone of GKE cluster to deploy to.
    required: true

  cluster_name:
    description: |-
      Name of GKE cluster to deploy to.
    required: true

  project_id:
    description: |-
      Project of GKE cluster to deploy to.
    required: true

  namespace:
    description: |-
      Namespace for the GKE cluster to deploy to.
      If not provided, it will not be passed to the binary. 
    required: true

  expose:
    description: |-
      The port provided will be used to expose the deployed workload object (i.e., port and targetPort will be set to the value provided in this flag). 
      If not provided, it will not be passed to the binary.
    required: true

runs:
  using: "composite"
  steps:
  - name: clone gke-deploy cli
    uses: actions/checkout@v4
    with:
      repository: GoogleCloudPlatform/cloud-builders

  - name: setup go
    uses: actions/setup-go@v4
    with:
      go-version: "1.19"

  - name: build gke-deploy go binary
    shell: bash
    run: |
      cd gke-deploy
      go build -o gke-deploy

  - name: deploy image
    shell: bash
    run: |
      echo $GOOGLE_APPLICATION_CREDENTIALS
      pwd
      sudo cp $GOOGLE_APPLICATION_CREDENTIALS ./gke-deploy
      cd gke-deploy
      echo "$IMAGE"
      ./gke-deploy run -i "$IMAGE" -a "$APP_NAME" -x "$EXPOSE" -c "$CLUSTER_NAME" -l "$REGION" -p "$PROJECT_ID" -n "$NAMESPACE"
    env:
      APP_NAME: ${{ inputs.app_name }}
      CLUSTER_NAME: ${{ inputs.cluster_name }}
      EXPOSE: ${{ inputs.expose }}
      IMAGE: ${{ inputs.image }}
      NAMESPACE: ${{ inputs.namespace }} 
      PROJECT_ID: ${{ inputs.project_id }}
      REGION: ${{ inputs.region }}
